### ISSUE TITLE
Bug sur le calcul des moyennes

### ISSUE THREAD

**Issue by foures** [sichida/BDD-examples#1]
Suite à la présentation faite au Paris JUG mardi dernier (merci encore), je m'amuse un peu avec ton code d'exemple sur cucumber. J'ai un doute sur le fonctionnement du code, mais je pense que c'est un bug.

Tu déclares, dans le fichier mark-conference.feature, deux scénarios. J'ai tenté d'écrire un troisième scénario qui affecte par deux fois des notes à un même orateur (afin de faire vérifier le calcul de la moyenne), mais le résultat est faux (car le calcul prend en compte la première note attribuée lors des autres scénarios).

Par scénario, je comprend un jeu de test « indépendant et étanche des autres », qui peut être exécuté avant ou après les autres, sans que le résultat ne change (comme pour les tests unitaires). Est-ce bien la notion utilisée par Cucumber pour définir les scénarios ? (je découvre cucumber.) Si c'est bien le cas, ne faudrait-il pas réinitialiser la « base de donnée » entre chaque scénario ?

Pour info, voici le contenu de mon fichier mark-conférence.feature :

``` gherkin
# language: fr
Fonctionnalité: noter une conférence
  En tant que technophile
  Je veux sélectionner une des conférence auxquelles j'ai assisté
  Afin de donner une note entre 0 et 10


  Scénario:
    Etant donné que "Charles" est authentifié
    Et que les conférences suivantes ont été présentées:
      | Speaker | Subject                                                             |
      | Shoun   | Réaliser une bonne recette grâce au concombre                       |
      | Xavier  | Spock, un framework de test venu d’une autre planète                |
      | Romain  | Une stack logicielle pour applications géolocalisées                |
      | Patrick | Pour un front plus digeste, saupoudrez de feuilles de thym !!       |
      | Walid   | La recette pour déployer des applications microservice avec Ansible |
      | Yoann   | Java Agent en Action                                                |
      | Fabrice | Maven, c'est bien, SBT c'est mieux!                                 |
    Lorsqu' il attribue la note de 5 la conférence de "Shoun"
    Alors la conférence de "Shoun" devrait avoir la note de 5

  Scénario: notes multiples
    Etant donné que "Charles" est authentifié
    Et que les conférences suivantes ont été présentées:
      | Speaker | Subject                                                             |
      | Shoun   | Réaliser une bonne recette grâce au concombre                       |
      | Xavier  | Spock, un framework de test venu d’une autre planète                |
      | Romain  | Une stack logicielle pour applications géolocalisées                |
      | Patrick | Pour un front plus digeste, saupoudrez de feuilles de thym !!       |
      | Walid   | La recette pour déployer des applications microservice avec Ansible |
      | Yoann   | Java Agent en Action                                                |
      | Fabrice | Maven, c'est bien, SBT c'est mieux!                                 |
    Lorsqu' il attribue la note de 5 la conférence de "Shoun"
    Alors la conférence de "Shoun" devrait avoir la note de 5
    Lorsqu' il attribue la note de 7 la conférence de "Shoun"
    Alors la conférence de "Shoun" devrait avoir la note de 6

  Scénario: scénario 2
    Etant donné que "Charles" est authentifié
    Et que les conférences suivantes ont été présentées:
      | Speaker | Subject                                                             |
      | Shoun   | Réaliser une bonne recette grâce au concombre                       |
      | Xavier  | Spock, un framework de test venu d’une autre planète                |
      | Romain  | Une stack logicielle pour applications géolocalisées                |
      | Patrick | Pour un front plus digeste, saupoudrez de feuilles de thym !!       |
      | Walid   | La recette pour déployer des applications microservice avec Ansible |
      | Yoann   | Java Agent en Action                                                |
      | Fabrice | Maven, c'est bien, SBT c'est mieux!                                 |
    Lorsqu' il attribue la note de 5 la conférence de "Xavier"
    Alors la conférence de "Xavier" devrait avoir la note de 5
```

**Comment by sichida** [comment]
Salut,

Bien vu pour ce bug. Effectivement la feature ne fonctionne pas correctement lorsque tu impacts une conférence déjà notée.
Le problème vient du fait que je n'utilise pas de base de donnée et donc pas de transaction qui peuvent être "rollbackées". Dans mon exemple, j'ai une liste dans une bean Spring, et contrairement à ce que je pensais, le context Spring n'est rechargé après chaque scénario ou feature, donc si on modifie cette liste elle garde son état au test suivant.

Pour répondre à ta problématique, j'ai ajouté la dimension base de donnée avec la gestion des transactions. Comme tu peux le voir, j'ai ajouté l'annotation @txn dans le Gherkin qui permet de rollbacker toutes les transactions de la feature.
Le fix se trouvent dans les commit :
https://github.com/sichida/BDD-examples/commit/843f223d882eed148078a6b85b7c61ef77d2790c
https://github.com/sichida/BDD-examples/commit/001353d1bd6247cc662b5a267a72db22aa0b6044

N'hésite pas à commenter cette issue si tu souhaites plus d'information.

**Comment by foures** [comment]
Salut,

Merci beaucoup pour ta correction. C'est d'autant plus intéressant d'appréhender Cucumber avant et après la réelle notion de base de données (et des transactions). Parfait pour un tutoriel, ça commence simple et ça devient ensuite concret avec la mise en place de la base de donnée :)

Juste une question complémentaire : sais-tu s'il est possible d'ajouter cette annotation directement dans les classes Java des définitions, cela afin d'épurer le code Gherkin d'aspects purement techniques. J'y vois plusieurs intérêts. Le premier est pour les utilisateurs métiers, cela évite d'avoir des directives « abscons » pour eux. Le second est de factoriser le fait que tous les fichiers `.feature` utilisant un même Stepsdefs soient traités à la même enseigne. Ce point permet d'une part de ne pas répéter le `@txn` dans chaque `.feature`, mais permet surtout de s'assurer que par défaut, tout nouveau `.feature` est traité via l'emploi de transactions rollbackées. Il devient donc impossible d'avoir des `.feature` transactionnelles et d'autres non transactionnelles. Cette homogénéité me paraît très importante pour la cohérence des jeux de tests. 

J'ai regardé rapidement et cela semble être possible avec des annotations `@Before` et `@After` dans le Stepsdefs en codant directement le début de transactions et le rollback consécutif (comme indiqué sur cette [page](https://cucumber.io/docs/reference/state)), ou de nettoyer à la main la base « avant » et/ou « après » chaque test, mais tout cela me semble « compliqué » pour un truc aussi utile / commun. Suis-je passé à côté de quelque chose ? J'ai essayé, par curiosité, de mettre un `@Transactional` dans les Stepsdefs (comme dans le ConferenceServiceTest) mais ça n'a pas marché. 

Merci encore,
Pierre.

**Comment by sichida** [comment]
Bonjour,

Désolé pour mon manque de réponse ces derniers temps...
Je n'ai pas vraiment d'alternative au @txn si ce n'est ce que tu as mentionné avec les méthodes @Before et @After.
De mon point de vue ce n'est pas problématique car la responsabilité de gérer les transactions revient aux développeurs. De ce fait, le PO n'a pas à ajouter l'annotation @txn (c'est un élément technique).

L'ajout de cet annotation de doit intervenir qu'au moment de l'implémentation de la feature.
J'espère que cette réponse te conviendra.
